name: Update Verifier

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-verifier:
    runs-on: ubuntu-latest
    steps:
      # Generate token for GitHub App
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      # Checkout with the app token
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
          persist-credentials: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Update verifier dependency
        run: |
          # Use Verifier Release Bot for commits
          git config --local user.email "1461927+verifier-release-bot[bot]@users.noreply.github.com"
          git config --local user.name "verifier-release-bot[bot]"
          go get -u github.com/tinfoilsh/verifier@latest

          # Check if there are any changes to commit
          if git diff --exit-code go.mod go.sum; then
            echo "No changes to verifier dependency"
          else
            git add go.mod go.sum
            git commit -m "chore: bump verifier to latest version"
            git push origin main
            echo "Update completed and pushed to remote."
          fi
